export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  //get profile
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  //get Notifaction
  GET_NOTIFACTION_REQUEST: "GET_NOTIFACTION_REQUEST",
  GET_NOTIFACTION_SUCCESS: "GET_NOTIFACTION_SUCCESS",
  GET_NOTIFACTION_FAILURE: "GET_NOTIFACTION_FAILURE",
  //get Favorite
  GET_FAVORITE_REQUEST: 'GET_FAVORITE_REQUEST',
  GET_FAVORITE_SUCCESS: 'GET_FAVORITE_SUCCESS',
  GET_FAVORITE_FAILURE: 'GET_FAVORITE_FAILURE',
  //add favorite
  ADD_FAVORITE_REQUEST: 'ADD_FAVORITE_REQUEST',
  ADD_FAVORITE_SUCCESS: 'ADD_FAVORITE_SUCCESS',
  ADD_FAVORITE_FAILURE: 'ADD_FAVORITE_FAILURE',
   //get Security Alert
   GET_SECURITY_ALERT_REQUEST: 'GET_SECURITY_ALERT_REQUEST',
   GET_SECURITY_ALERT_SUCCESS: 'GET_SECURITY_ALERT_SUCCESS',
   GET_SECURITY_ALERT_FAILURE: 'GET_SECURITY_ALERT_FAILURE',
};
