// live hosts

export default urls = {
  HOST: "https://billify.egreatminds.com/WebApi/",
  BASE_URL: "https://billify.egreatminds.com/WebApi/",
  //Login
  LOGIN: "api/Auth/Login",
  GET_PROPERTY: 'api/Lookup/GetPropertyType',
  GET_FLOOR_STORY: 'api/Lookup/GetFloorStory/id?id=',
  GET_USER: 'api/Users/GetUser',
  EDIT_PROFILE: 'api/Users/EditUser',
  GET_HEADER_SLIDER: 'api/HeaderSlider/GetHeaderSliderAll',
  ADD_TANENT: 'api/Users/AddTanent',
  UPDATE_TANENT: 'api/Users/UpdateTanent/',
  DELETE_TANENT: 'api/Users/DeleteTanent/',
  GET_ALL_BILLS: 'api/Bills/GetBillDetail/',
  GET_BILLS_DETAILS: 'api/Bills/GetBillDetail/',
  GET_CATEGORY: 'api/ComplainType/GetComplainTypeAll',
  GET_PRE_COMPLAIN: 'api/ComplainType/GetPreDefineComplains/',
  ADD_COMPLAINTS: 'api/Complaints/AddComplaint',
  GET_COMPLAINT_BY_CATEGORY: 'api/Complaints/GetComplaintbyCategory',
  GET_COMPLAINT_ALL: 'api/Complaints/GetComplaintAllByUser',
  GET_COMPLAINT_DETAIL: 'api/Complaints/GetComplaintForWorker?complaintid=',
  GET_COMPLAINT_DETAIL_USER:'api/Complaints/GetComplaintAllByUser?complaintid=',
  GET_MANAGER_COMPLAINTS: 'api/Complaints/GetComplaintForManager',
  GET_COMP_LOOKUP: 'api/Lookup/GetSocietyWorkers/',
  UPDATE_WORKER: 'api/Complaints/AssignedComplain/',
  GET_MANAGER_PROFILE: 'api/Users/GetManagersDetail',
  // GET_WORKER_PROFILE:'api/Complaints/GetComplaintForWorker',
  // GET_WORKER_DATA: 'api/Complaints/GetWorkerAssignedComplaintAll/',
  GET_WORKER_DATA: 'api/Complaints/GetComplaintForWorker',
  GET_PAYMENT_METHOD: 'api/Lookup/GetPaymentMethods',
  ADD_BILL_PAYMENT: 'api/BillPayment/AddBillPayment',
  ADD_SELL_PRODUCT: 'api/UserSalePurchase/AddUserSalePurchase',
  GET_USER_PURCHASE: 'api/UserSalePurchase/GetUserSalePurchaseAll',
  WANT_TO_BUY: 'api/ProductRequest/AddProductRequest',
  GET_PRODUCT: 'api/ProductRequest/GetProductRequestAll',
  GET_NOTIFICATION: 'api/Notification/GetNotification',
  GET_USER_PRODUCT_SALE: 'api/UserSalePurchase/GetUserProductSaleAd',
  GET_ALL_FAVORITE: 'api/UserSalePurchase/GetAllFavouriteAd',
  ADD_FAVORITE_PRODUCT: 'api/UserSalePurchase/AdFavourites',
  REMOVE_FAVORITE: 'api/UserSalePurchase/RemoveAdFromFavourites/',
  GET_SOCIETY_EVENTS:'api/Events/GetSocietyEventsAll/',
  PRODUCT_DELETE:'api/UserSalePurchase/DeleteAd/',
  BY_USER_WANT_TO_BUY:'api/ProductRequest/GetProductRequestAll?userId=',
  PRODUCT_REQUEST_DELETE:'api/ProductRequest/DeleteProductRequest/',
  Delete_Notification_ALL:'api/Notification/DeleteNotification/',
  UPDATE_NOTIFICATIONS:'api/Notification/UpdateNotification/',
  UPDATE_COMPLAINT_STATUS:'api/Complaints/UpdateAssignedComplain/',
  GET_SECURITY_ALERT:'api/Notification/GetSocietyAlerts/0',
  Delete_Notification_SOCIETY:'api/Notification/DeleteSocietyAlerts/',
  GET_SHUTTLE_SERVICE:'api/Shuttle/GetShuttleServiceAll',
  GET_TRANSACTION_HISTORY:'api/BillPayment/GetBillPaymentsAll',
  COMPLAIN_CONFIRMATION_USER:'api/Complaints/AssignedComplainConfirmationFromUser/',
  GET_MANAGER_NOTIFACTION:'api/Notification/GetNotificationForManager',
  GET_COMPLAINT_ALL_TYPE:'api/ComplainType/GetComplainTypeAll',
};
